-- 001_arabic_surah_names.sql
-- Seed Arabic Surah names for reference

CREATE TABLE IF NOT EXISTS surah_names (
    surah_number INTEGER PRIMARY KEY,
    arabic_name TEXT NOT NULL,
    english_name TEXT
);

INSERT OR IGNORE INTO surah_names (surah_number, arabic_name, english_name) VALUES
(1, 'الفاتحة', 'Al-Fatihah'),
(2, 'البقرة', 'Al-Baqarah'),
(3, 'آل عمران', 'Ali Imran'),
(4, 'النساء', 'An-Nisa'),
(5, 'المائدة', 'Al-Maidah'),
(6, 'الأنعام', 'Al-Anam'),
(7, 'الأعراف', 'Al-Araf'),
(8, 'الأنفال', 'Al-Anfal'),
(9, 'التوبة', 'At-Tawbah'),
(10, 'يونس', 'Yunus'),
(11, 'هود', 'Hud'),
(12, 'يوسف', 'Yusuf'),
(13, 'الرعد', 'Ar-Rad'),
(14, 'إبراهيم', 'Ibrahim'),
(15, 'الحجر', 'Al-Hijr'),
(16, 'النحل', 'An-Nahl'),
(17, 'الإسراء', 'Al-Isra'),
(18, 'الكهف', 'Al-Kahf'),
(19, 'مريم', 'Maryam'),
(20, 'طه', 'Ta-Ha'),
(21, 'الأنبياء', 'Al-Anbiya'),
(22, 'الحج', 'Al-Hajj'),
(23, 'المؤمنون', 'Al-Muminun'),
(24, 'النور', 'An-Nur'),
(25, 'الفرقان', 'Al-Furqan'),
(26, 'الشعراء', 'Ash-Shuara'),
(27, 'النمل', 'An-Naml'),
(28, 'القصص', 'Al-Qasas'),
(29, 'العنكبوت', 'Al-Ankabut'),
(30, 'الروم', 'Ar-Rum'),
(31, 'لقمان', 'Luqman'),
(32, 'السجدة', 'As-Sajdah'),
(33, 'الأحزاب', 'Al-Ahzab'),
(34, 'سبأ', 'Saba'),
(35, 'فاطر', 'Fatir'),
(36, 'يس', 'Ya-Sin'),
(37, 'الصافات', 'As-Saffat'),
(38, 'ص', 'Sad'),
(39, 'الزمر', 'Az-Zumar'),
(40, 'غافر', 'Ghafir'),
(41, 'فصلت', 'Fussilat'),
(42, 'الشورى', 'Ash-Shura'),
(43, 'الزخرف', 'Az-Zukhruf'),
(44, 'الدخان', 'Ad-Dukhan'),
(45, 'الجاثية', 'Al-Jathiyah'),
(46, 'الأحقاف', 'Al-Ahqaf'),
(47, 'محمد', 'Muhammad'),
(48, 'الفتح', 'Al-Fath'),
(49, 'الحجرات', 'Al-Hujurat'),
(50, 'ق', 'Qaf'),
(51, 'الذاريات', 'Adh-Dhariyat'),
(52, 'الطور', 'At-Tur'),
(53, 'النجم', 'An-Najm'),
(54, 'القمر', 'Al-Qamar'),
(55, 'الرحمن', 'Ar-Rahman'),
(56, 'الواقعة', 'Al-Waqiah'),
(57, 'الحديد', 'Al-Hadid'),
(58, 'المجادلة', 'Al-Mujadila'),
(59, 'الحشر', 'Al-Hashr'),
(60, 'الممتحنة', 'Al-Mumtahinah'),
(61, 'الصف', 'As-Saff'),
(62, 'الجمعة', 'Al-Jumuah'),
(63, 'المنافقون', 'Al-Munafiqun'),
(64, 'التغابن', 'At-Taghabun'),
(65, 'الطلاق', 'At-Talaq'),
(66, 'التحريم', 'At-Tahrim'),
(67, 'الملك', 'Al-Mulk'),
(68, 'القلم', 'Al-Qalam'),
(69, 'الحاقة', 'Al-Haqqah'),
(70, 'المعارج', 'Al-Marij'),
(71, 'نوح', 'Nuh'),
(72, 'الجن', 'Al-Jinn'),
(73, 'المزمل', 'Al-Muzzammil'),
(74, 'المدثر', 'Al-Muddathir'),
(75, 'القيامة', 'Al-Qiyamah'),
(76, 'الإنسان', 'Al-Insan'),
(77, 'المرسلات', 'Al-Mursalat'),
(78, 'النبأ', 'An-Naba'),
(79, 'النازعات', 'An-Nazi at'),
(80, 'عبس', 'Abasa'),
(81, 'التكوير', 'At-Takwir'),
(82, 'الانفطار', 'Al-Infitar'),
(83, 'المطففين', 'Al-Mutaffifin'),
(84, 'الانشقاق', 'Al-Inshiqaq'),
(85, 'البروج', 'Al-Buruj'),
(86, 'الطارق', 'At-Tariq'),
(87, 'الأعلى', 'Al-Ala),
(88, 'الغاشية', 'Al-Ghashiyah'),
(89, 'الفجر', 'Al-Fajr'),
(90, 'البلد', 'Al-Balad'),
(91, 'الشمس', 'Ash-Shams'),
(92, 'الليل', 'Al-Layl'),
(93, 'الضحى', 'Ad-Duha'),
(94, 'الشرح', 'Ash-Sharh'),
(95, 'التين', 'At-Tin'),
(96, 'العلق', 'Al-Alaq'),
(97, 'القدر', 'Al-Qadr'),
(98, 'البينة', 'Al-Bayyinah'),
(99, 'الزلزلة', 'Az-Zalzalah'),
(100, 'العاديات', 'Al-Adiyat'),
(101, 'القارعة', 'Al-Qariah'),
(102, 'التكاثر', 'At-Takathur'),
(103, 'العصر', 'Al-Asr'),
(104, 'الهمزة', 'Al-Humazah'),
(105, 'الفيل', 'Al-Fil'),
(106, 'قريش', 'Quraysh'),
(107, 'الماعون', 'Al-Maun'),
(108, 'الكوثر', 'Al-Kawthar'),
(109, 'الكافرون', 'Al-Kafirun'),
(110, 'النصر', 'An-Nasr'),
(111, 'المسد', 'Al-Masad'),
(112, 'الإخلاص', 'Al-Ikhlas'),
(113, 'الفلق', 'Al-Falaq'),
(114, 'الناس', 'An-Nas');
